import React, { useEffect, useState } from 'react';
import { ImageOverlay, MapContainer, Rectangle } from 'react-leaflet';
import L from 'leaflet';
import { downloadPdf, getJob, login, submitJob } from './api';
import './app.css';

const stages = ['LOGIN', 'DATA', 'VALIDATION', 'CLASSIFICATION', 'ANALYSIS', 'REPORT'];

function StageNav({ current, onNavigate }) {
  return <nav className="stage-nav" aria-label="Analysis progress">{stages.map((stage, index) => <button key={stage} className={current === stage ? 'stage active' : 'stage'} type="button" onClick={() => index < stages.indexOf(current) && onNavigate(stage)}><span>{String(index + 1).padStart(2, '0')}</span>{stage}</button>)}</nav>;
}

function Page({ eyebrow, title, onBack, children }) {
  return <main className="page"><div className="page-heading"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{onBack && <button className="back-button" type="button" onClick={onBack}>Back</button>}</div>{children}</main>;
}

function FileInput({ label, file, optional, onChange }) {
  return <label className={`file-input ${file ? 'selected' : ''}`}><span className="field-label">{label} {optional && <small>OPTIONAL</small>}</span><strong>{file?.name || 'Choose GeoTIFF, TIFF, PNG, or JPEG'}</strong><span>{file ? `${(file.size / 1024 / 1024).toFixed(2)} MB` : 'Satellite imagery input'}</span><input type="file" accept="image/*,.tif,.tiff" onChange={(event) => onChange(event.target.files?.[0] || null)} /></label>;
}

function Metric({ label, value }) { return <div className="metric"><span>{label}</span><strong>{value || '--'}</strong></div>; }

function Trace({ result }) {
  const steps = result?.execution_trace?.steps || [];
  return <section className="trace"><div className="section-heading"><span>Execution trace</span><small>Backend-emitted events</small></div>{steps.map((step, index) => <div className="trace-step" key={`${step.node || 'event'}-${index}`}><b className={step.status === 'failed' ? 'trace-icon failed' : 'trace-icon'}>{step.status === 'failed' ? '!' : '✓'}</b><div><strong>{(step.node || 'workflow event').replaceAll('_', ' ')}</strong><small>{step.selected_task || step.model || step.inference_mode || step.reason || step.status || 'completed'}</small></div></div>)}</section>;
}

function Validation({ result, onBack, onNext }) {
  const failed = result?.status === 'error';
  const steps = result?.execution_trace?.steps || [{ node: 'validate_inputs', status: failed ? 'failed' : 'passed' }];
  return <Page eyebrow="02 / VALIDATION" title="Input integrity & compatibility" onBack={onBack}><div className="status-banner"><b className={failed ? 'status-mark failed' : 'status-mark'}>{failed ? '!' : '✓'}</b><div><strong>{failed ? 'Validation failed' : 'Input accepted'}</strong><p>{failed ? result.detail : 'The service accepted the submitted files for analysis.'}</p></div></div><div className="check-list">{steps.map((step, index) => <div className="check-row" key={`${step.node}-${index}`}><b className={step.status === 'failed' ? 'check failed' : 'check'}>{step.status === 'failed' ? '!' : '✓'}</b><span>{(step.node || 'check').replaceAll('_', ' ')}</span><small>{step.status || 'reported'}</small></div>)}</div>{!failed && <button className="primary-button" type="button" onClick={onNext}>Continue to classification <span>→</span></button>}</Page>;
}

export default function App() {
  const [stage, setStage] = useState('LOGIN'); const [token, setToken] = useState('');
  const [primary, setPrimary] = useState(null); const [comparison, setComparison] = useState(null);
  const [query, setQuery] = useState(''); const [result, setResult] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const [credentials, setCredentials] = useState({ username: '', password: '' });
  async function authenticate(event) { event.preventDefault(); setError(''); try { setToken(await login(credentials.username, credentials.password)); setStage('DATA'); } catch (requestError) { setError(requestError.message); } }
  async function analyze(event) { event.preventDefault(); if (!primary || !query.trim()) return; setLoading(true); setError(''); try { const submitted = await submitJob({ primary, comparison, query, token }); let job = submitted; while (job.status === 'QUEUED' || job.status === 'PROCESSING') { await new Promise((resolve) => setTimeout(resolve, 500)); job = await getJob(submitted.job_id, token); } if (job.status !== 'COMPLETED') throw new Error(job.error || 'The analysis job failed.'); setResult(job.result); setStage('VALIDATION'); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } }
  const route = result?.route || {}; const overlay = result?.overlay_b64 || result?.annotated_image_b64; const source = primary && !/\.tiff?$/i.test(primary.name) ? URL.createObjectURL(primary) : null; const boxes = (result?.bounding_boxes || []).map((box) => Array.isArray(box) ? box : box.coordinates).filter((box) => Array.isArray(box) && box.length === 4 && box.every((value) => Number.isFinite(Number(value))));
  useEffect(() => () => source && URL.revokeObjectURL(source), [source]);
  return <div className="app-shell"><header className="topbar"><a className="brand" href="#top"><span className="brand-mark">SQ</span><span>SatQuery <em>AI</em></span></a><span className="system-status"><i /> Remote sensing intelligence platform</span></header>{stage !== 'LOGIN' && <StageNav current={stage} onNavigate={setStage} />}
  {stage === 'LOGIN' && <Page eyebrow="SATQUERY AI / WORKSPACE" title="Remote sensing intelligence platform"><form className="login-panel" onSubmit={authenticate}><p>Prototype access to the SatQuery analysis workspace.</p><label>Username / Employee ID<input required value={credentials.username} onChange={(event) => setCredentials({ ...credentials, username: event.target.value })} placeholder="analyst.demo" /></label><label>Password<input required type="password" value={credentials.password} onChange={(event) => setCredentials({ ...credentials, password: event.target.value })} placeholder="satquery-demo" /></label>{error && <div className="error-message" role="alert">{error}</div>}<button className="primary-button">Secure login <span>→</span></button><small className="disclaimer">Prototype credentials are environment-configured. No government or ISRO authentication is claimed.</small></form></Page>}
  {stage === 'DATA' && <Page eyebrow="01 / DATA" title="Upload & query"><form className="data-form" onSubmit={analyze}><div className="file-grid"><FileInput label="Primary image" file={primary} onChange={setPrimary} /><FileInput label="Comparison image" optional file={comparison} onChange={setComparison} /></div><label className="query-field"><span className="field-label">Analysis query <small>{query.length}/240</small></span><textarea maxLength="240" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Enter a focused question about the imagery" /></label>{error && <div className="error-message" role="alert">{error}</div>}<button className="primary-button" disabled={loading || !primary || !query.trim()}>{loading ? 'Submitting analysis...' : 'Analyze imagery'} <span>→</span></button></form></Page>}
  {stage === 'VALIDATION' && <Validation result={result} onBack={() => setStage('DATA')} onNext={() => setStage('CLASSIFICATION')} />}
  {stage === 'CLASSIFICATION' && <Page eyebrow="03 / CLASSIFICATION" title="Task classification" onBack={() => setStage('VALIDATION')}><div className="classification"><span className="eyebrow">Detected task</span><strong className="task-name">{route.task || 'Unknown'}</strong><p>{route.reason || 'No routing reason was returned.'}</p><div className="detail-grid"><Metric label="Required inputs" value={comparison ? 'Paired imagery' : 'Single image'} /><Metric label="Workflow" value={route.task} /><Metric label="Confidence" value={result?.confidence ? `${Math.round(result.confidence * 100)}%` : 'Not emitted'} /></div></div><Trace result={result} /><button className="primary-button" type="button" onClick={() => setStage('ANALYSIS')}>View analysis <span>→</span></button></Page>}
  {stage === 'ANALYSIS' && <Page eyebrow="04 / ANALYSIS" title="Analysis result" onBack={() => setStage('CLASSIFICATION')}><div className="answer-card"><span className="eyebrow">Final answer</span><p>{result?.answer || result?.detail || 'No answer returned.'}</p></div><div className="detail-grid"><Metric label="Detected task" value={route.task} /><Metric label="Confidence" value={result?.confidence ? `${Math.round(result.confidence * 100)}%` : '--'} /><Metric label="Inference" value={result?.execution_trace?.steps?.at(-1)?.inference_mode || 'Specialist'} /></div>{(overlay || source) && <div className="map-frame"><MapContainer className="map" center={[0, 0]} zoom={1} crs={L.CRS.Simple} scrollWheelZoom={false}><ImageOverlay url={overlay ? `data:image/png;base64,${overlay}` : source} bounds={[[-100, -100], [100, 100]]} />{boxes.map((box, index) => <Rectangle key={index} bounds={[[100 - box[0], box[1] - 100], [100 - box[2], box[3] - 100]]} pathOptions={{ color: '#d9694b', weight: 2 }} />)}</MapContainer></div>}<Trace result={result} /><button className="primary-button" type="button" onClick={() => setStage('REPORT')}>Prepare report <span>→</span></button></Page>}
  {stage === 'REPORT' && <Page eyebrow="05 / REPORT" title="Evidence report" onBack={() => setStage('ANALYSIS')}><div className="report-sheet"><span className="eyebrow">SatQuery AI / analysis record</span><Metric label="Query" value={query} /><Metric label="Task" value={route.task} /><Metric label="Confidence" value={result?.confidence ? `${Math.round(result.confidence * 100)}%` : '--'} /><div className="report-answer">{result?.answer}</div><Trace result={result} /></div><div className="button-row"><button className="secondary-button" type="button" disabled={!result?.report_pdf_b64} onClick={() => downloadPdf(result.report_pdf_b64)}>Generate PDF</button><button className="primary-button" type="button" onClick={() => { setResult(null); setPrimary(null); setComparison(null); setQuery(''); setStage('DATA'); }}>New analysis <span>→</span></button></div></Page>}
  <footer>SatQuery AI / Earth observation toolkit <span>Results are advisory and should be reviewed by an analyst.</span></footer></div>;
}
